# Generated by Django 5.0.1 on 2024-01-24 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GERENCIAMENTO_PEDIDOS_APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='pedidos',
        ),
        migrations.CreateModel(
            name='ProdutoQuantidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_produtos', models.IntegerField()),
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='produtos_pedidos', to='GERENCIAMENTO_PEDIDOS_APP.produto')),
            ],
            options={
                'verbose_name': 'Produto pedido',
                'verbose_name_plural': 'Produtos pedidos',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='produtos_quantidades',
            field=models.ManyToManyField(to='GERENCIAMENTO_PEDIDOS_APP.produtoquantidade'),
        ),
        migrations.DeleteModel(
            name='Produto_pedido',
        ),
    ]
