# Generated by Django 5.0.1 on 2024-01-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GERENCIAMENTO_PEDIDOS_APP', '0002_remove_produto_pedidos_produtoquantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='produtos_quantidades',
            field=models.ManyToManyField(blank=True, to='GERENCIAMENTO_PEDIDOS_APP.produtoquantidade'),
        ),
    ]
